import type { Product } from "@/types";

// 데모 데이터 — 백엔드 미연결 시 UI 확인용
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "p1719000001",
    createdAt: "2026-06-28T10:00:00Z",
    status: "판매중",
    deal: "나눔",
    category: "전산소모품",
    title: "HP 26A 토너 미개봉",
    price: 0,
    desc: "프린터 교체로 남은 미개봉 토너입니다. 5층에서 픽업 가능해요.",
    loc: "본사 5층",
    nick: "오이박사",
    uid: "demo-uid-1",
    photoURL: "",
    jjim: 3,
    chats: 1,
  },
  {
    id: "p1719000002",
    createdAt: "2026-06-27T14:30:00Z",
    status: "판매중",
    deal: "판매",
    category: "전산소모품",
    title: "삼성 MLT-D111S 토너 카트리지",
    price: 25000,
    desc: "호환 아닌 정품입니다. 밀봉 상태. 택배 불가, 직접 수령만.",
    loc: "별관 A동",
    nick: "절약의신",
    uid: "demo-uid-2",
    photoURL: "",
    jjim: 7,
    chats: 2,
  },
  {
    id: "p1719000003",
    createdAt: "2026-06-26T09:15:00Z",
    status: "판매중",
    deal: "나눔",
    category: "사무용품",
    title: "A4용지 반박스 (1,250매)",
    price: 0,
    desc: "팀 이동으로 남은 A4용지. 한 박스 반 정도입니다.",
    loc: "본사 3층",
    nick: "나눔요정",
    uid: "demo-uid-3",
    photoURL: "",
    jjim: 12,
    chats: 4,
  },
  {
    id: "p1719000004",
    createdAt: "2026-06-25T16:45:00Z",
    status: "판매중",
    deal: "판매",
    category: "가구·비품",
    title: "허먼밀러 세이프 의자 팔걸이",
    price: 35000,
    desc: "모델 교체하며 분리한 팔걸이입니다. 양쪽 세트, 상태 좋아요.",
    loc: "분당 사무소",
    nick: "의자왕",
    uid: "demo-uid-4",
    photoURL: "",
    jjim: 5,
    chats: 3,
  },
  {
    id: "p1719000005",
    createdAt: "2026-06-24T11:20:00Z",
    status: "판매중",
    deal: "나눔",
    category: "전산소모품",
    title: "USB-C to HDMI 케이블 2m",
    price: 0,
    desc: "회의실 모니터 교체로 남은 케이블. 정상 동작합니다.",
    loc: "본사 2층",
    nick: "IT관리자",
    uid: "demo-uid-5",
    photoURL: "",
    jjim: 2,
    chats: 0,
  },
  {
    id: "p1719000006",
    createdAt: "2026-06-23T08:00:00Z",
    status: "거래완료",
    deal: "판매",
    category: "사무용품",
    title: "3M 포스트잇 대용량 팩 (미개봉)",
    price: 8000,
    desc: "팀 비품으로 사둔 건데 안 쓰게 되어서 올립니다.",
    loc: "판교 사무소",
    nick: "정리왕",
    uid: "demo-uid-6",
    photoURL: "",
    jjim: 4,
    chats: 2,
  },
  {
    id: "p1719000007",
    createdAt: "2026-06-22T13:50:00Z",
    status: "판매중",
    deal: "판매",
    category: "기타",
    title: "로지텍 MX Master 3S 마우스",
    price: 65000,
    desc: "1년 사용, 상태 양호. 충전 케이블 포함. 리시버 분실.",
    loc: "본사 4층",
    nick: "가젯매니아",
    uid: "demo-uid-7",
    photoURL: "",
    jjim: 15,
    chats: 6,
  },
  {
    id: "p1719000008",
    createdAt: "2026-06-21T10:30:00Z",
    status: "판매중",
    deal: "나눔",
    category: "사무용품",
    title: "화이트보드 마커 세트 (12색)",
    price: 0,
    desc: "브레인스토밍용으로 샀는데 이제 디지털 보드로 바꿔서 나눔합니다.",
    loc: "별관 B동",
    nick: "나눔천사",
    uid: "demo-uid-8",
    photoURL: "",
    jjim: 1,
    chats: 0,
  },
];
